# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 866f884c419223ef59817028563a172cc7089793f260688928fdbd811645c892672c6ec9505e61bab47c56faafe1a88a424a5608d4f06d856c49cf47fd69bee6

test:
  secret_key_base: ad9d4c7f36ac7c109bb1059b0ef6dabdefe2986827895e1386df5f2bfd3b4ee711086330b04091c6b435e3d2e19d9daf76d3cf29c4c32f7a65f0c95fae7a3df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
